#!/bin/bash

cd ${OPENSHIFT_RAILO4j_DIR}/versions/9.1.3/

if [ -x /opt/repo/versions/9.1.3/bin/variablesparser.sh ]; then
    . /opt/repo/versions/9.1.3/bin/variablesparser.sh
fi

[ -z "$XMS" ] && { XMS=32M; }
[ -z "$XMN" ] && { XMN=30M; }
[ -z "$GC" ] && { GC="-XX:+UseParNewGC"; }
memory_total=`free -m | grep Mem | awk '{print $2}'`;
[ -z "$XMX" ] && { let XMX=memory_total-35; XMX="${XMX}M"; }

CMD="java -Xms${XMS} -Xmx${XMX} -Xmn${XMN} -jar start.jar -Djetty.host=$OPENSHIFT_RAILO4j_APP_HOST -Djetty.port=$OPENSHIFT_RAILO4j_APP_PORT ${GC} ${confresult}";

nohup $CMD > $OPENSHIFT_RAILO4j_LOG_DIR/server.log 2>&1 &

echo $! > jetty.pid && echo "Railo server started successfully"


