#!/bin/bash

cd ${OPENSHIFT_RAILO4j_DIR}/versions/9.1.3/

CMD="java -Xms32m -Xmx2013m -jar start.jar -Djetty.host=$OPENSHIFT_RAILO4j_APP_HOST -Djetty.port=$OPENSHIFT_RAILO4j_APP_PORT"

nohup $CMD > $OPENSHIFT_RAILO4j_LOG_DIR/server.log 2>&1 &

echo $! > jetty.pid


